name: fl_location
description: A plugin that can access the location services of each platform and collect device location data.
homepage: https://github.com/Dev-hwang/flutter_location/tree/master/fl_location
version: 2.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  fl_location_platform_interface:
    git:
      url: https://github.com/ShineYang/flutter_location.git
      path: fl_location_platform_interface
      ref: master

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.pravera.fl_location
        pluginClass: FlLocationPlugin
      ios:
        pluginClass: FlLocationPlugin
      web:
        default_package: fl_location_web
